[Navbar]

[header center: [title(1): ERROR HANDLING AND OPTIONALS]]
[main:

Errors are treated as values in Beanstalk, 
any function that can return an error must have its error handled.

The ? operator is used to signify an option of a type or none.

The ! operator is used to signify an option of an error or none.

Both can be combined in the case that None, Error or a data type can be returned.

You can also use these operators to unwrap a None or Error value. 
If it is, the error can then be handled immediately on the same line, or in a new block using a colon.

If you use a colon after the ? or ! operator, you will need an end statement to close the scope. 
Otherwise, you can handle it inline.

[code:
    func_call_that_can_return_an_error() !:
        -- Error handling code
    end

    -- This function can return a String or None
    parent_func () -> string?:
        return func_call_that_can_return_an_error() !:
            print("Error: ", error)
            return None
        end
    end
]

## Using the ? operator

[code:
    getURL () -> string:
        return getNetworkRequest() ?:
            print("Network did not respond: Using default URL")
            return "example.com"
        end
    end

    -- Returns a string or None
    getURL () -> string?:
        return getNetworkRequest()
    end
]

## Asserts and Panics
There are cases where you want to either catch unexpected state for debugging, 
or prevent the program from continuing if a certain condition is not met or an error is thrown.

For these cases the panic is used to mark functions that can panic explicitly at runtime.
You can't use the panic keyword unless the function has a panic as one if it's possible return values.

You can also create asserts that will stop the program if a condition is not met. 
These are removed by the compiler in release builds.

Functions that can panic at runtime should only be used in cases where the program should absolutely not continue if the function fails.
Such as if there is a high risk of undefined behaviour in a critical and complex part of a program.
Effectively creating a runtime assertion.

[code:
    -- stops the program if 1 is not equal to 1
    -- Runs the code in the block first
    assert(1 is not 1, "1 is not 1 uh oh")

    function_that_can_panic fn(the_truth Bool) -> panic?:
        if the_truth is False: panic("The truth is not true")
        
        -- This code will not run if the_truth is false
        return None
    end
]

[Footer]